name: shelf_helmet
description: A port of the NodeJS helmet package to Dart. Helmet helps you secure your Dart Shelf/Frog apps by setting various HTTP headers.
version: 1.1.0
homepage: https://jxstxn.de
repository: https://github.com/jxstxn1/shelf_helmet
issue_tracker: https://github.com/jxstxn1/shelf_helmet/issues

topics:
  - shelf
  - security
  - helmet
  - dart
  - dart_frog
  - dartlang
  - middleware
  - shelf_helmet

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  shelf: ^1.4.0

dev_dependencies:
  lint: ^1.0.0
  test: ^1.16.0
